* Timepix analysis & calibration

  #+ATTR_HTML: title="Join the chat at https://gitter.im/TimepixAnalysis/Lobby"
  [[https://gitter.im/TimepixAnalysis/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge][file:https://badges.gitter.im/TimepixAnalysis/Lobby.svg]]

This repository contains code related to the data analysis of Timepix
based gaseous detectors. 

It contains code to calibrate a Timepix ASIC and perform event shape
analysis of data to differentiate between background events (mainly
cosmic muons) and signal events (X-rays).

...

** CAST

Many parts of this repository are specifically related to an InGrid
based X-ray detector in use at the CERN Axion Solar Telescope:
[[http://cast.web.cern.ch/CAST/]]

...


* Project structure
This repository contains a big project combining several tools used
analyze data based Timepix based detectors as well as the CAST
experiment.

*NOTE:* If you are mainly interested in using the reconstruction and analysis
utilities for TOS data, the [[file:Analysis/][Analysis]] folder is what you're looking
for. See the [[Installation]] section for more information.

- [[file:Analysis/][Analysis]]: 
  Is the =ingrid= module, which contains the major programs of this
  repository [[file:Analysis/ingrid/raw_data_manipulation.nim][raw_data_manipulation]] and [[file:Analysis/ingrid/reconstruction.nim][reconstruction]] and to a lesser
  extent (depending on your use case) [[file:Analysis/ingrid/likelihood.nim][likelihood]]. 
  - [[file:Analysis/ingrid/raw_data_manipulation.nim][raw_data_manipulation]]:
    Reads folders of raw TOS data and outputs to a HDF5 file.
    Supported TOS data types:
    - old ~2015 era Virtex V6 TOS
    - current Virtex TOS
    - *soon:* current SRS TOS
  - [[file:Analysis/ingrid/reconstruction.nim][reconstruction]]:
    Takes the output of the above program and performs reconstruction
    of clusters within the data, i.e. calculate geometric properties.
  - [[file:Analysis/ingrid/likelihood.nim][likelihood]]: 
    Performs an event shape likelihood based analysis on
    the reconstructed data comparing with reference X-ray datasets.
  The other files in the folder are imported by these programs. An
  exception is skeleton program [[file:Analysis/ingrid/analysis.nim][analysis]], which will eventually become
  a wrapper of the other programs so that a nicer interface can be
  provided. A combination of a https://github.com/yglukhov/nimx based
  GUI with a =readline= based command line interface will be
  developed. 
- [[file:CDL-RootToHdf5/][CDL-RootToHdf5]]:
  A Python tool to (currently only) convert X-ray calibration data
  from the CAST detector lab from ROOT trees to HDF5 files. This could
  be easily extended to be a ROOT to HDF5 converter.
  TODO: this should be moved to [[file:Tools/][Tools]].
- [[file:endTimeExtractor/][endTimeExtractor]]:
  A Nim tool to extract the following information from a TOS run:
  - start of the Run
  - end of the Run
  - total run time
  and output it as an Org date string.
  TODO: should be moved to [[file:Tools/][Tools]].
- [[file:extractScintiTriggers/][extractScintiTriggers]]:
  A Nim tool to extract the number of scintillator triggers of a TOS
  run (either read from a raw run folder or a HDF5 file). Outputs
  total numbers of those and provides functionality to copy raw files
  containing non trivial scintillator counts (=< 4095= cycles) to a
  different location to view them with TOS's event display.
  TODO: should be moved to [[file:Tools/][Tools]].
- [[file:Figs/][Figs]]:
  Plots, which are created from the analysis and have been used in a
  talk etc.
- [[file:InGridDatabase/][InGridDatabase]]:
  A Nim program which provides, writes to and reads from the /InGrid
  database/. If the a folder describing the used detector is given to
  it (containing =fsr=, =threshold=, =thresholdMeans=, =ToT=
  calibration and / or =SCurves= and an additional file containing the
  chip name and additional information) it can be added to that
  database, which is simply a HDF5 file. The analysis progam makes use
  of this database to read calibration relevant data from it.
  TODO: link to explanation of required folder structure and add files
  / folders for current chips part of database.
- [[file:InGrid-Python/][InGrid-Python]]:
  A Python module containing additional functions used in the Nim
  analysis (fit of Fe55 spectrum and polya gas gain fit done using
  https://github.com/yglukhov/nimpy) and the Python plotting tool (see
  below). 
- [[file:LogReader/][LogReader]]:
  A Nim tool to read and process CAST slow control and tracking log
  files. From these environmental sensors can be read if needed for
  data analysis puposes of CAST data as well as information about when
  solar trackings took place. If a HDF5 file is given the tracking
  information is added to the appropriate runs.
- [[file:NimUtil][NimUtil]]:
  The =helpers= nimble module. It contains general procedures used in the rest
  of the code, which are unrelated to CAST or Timepix detectors.
- [[file:Plotting/][Plotting]]:
  A Nim tool to create plots of Timepix calibration data. Reads from
  the InGrid database and plots =ToT= calibration (+ fits) and
  SCurves.
- [[file:PlottingPython/][PlottingPython]]:
  A set of Python plotting tools. 
  - [[file:PlottingPython/Plotting/PyS_createBackgroundRate.py][PyS_createBackgroundRate.py]]: 
    used to create the background rate plots for the CAST data taking
    after the likelihood analysis has been performed.
  - [[file:PlottingPython/Plotting/PyS_plotH5data.py][PyS_plotH5data.py]]:
    used to plot arbitrary 1D column data (basically everything
    resulting from the reconstruction) from the reconstruction HDF5
    files.
- [[file:README.org][README.org]]: this file. :)
- [[file:resources/][resources]]:
  Contains data, which is needed for analysis purposes,
  e.g. information about run numbers for data taking periods, the
  2014/15 background rates etc.
  TODO: maybe add folders for known chips for InGrid database in here
  or at least an example directory.
- [[file:SolarEclipticToEarth][SolarEclipticToEarth]]: 
  A simple Python tool part of solar chameleon
  analysis, which calculates the projection of the solar ecliptic onto
  Earth (chameleon flux potentially varies greatly depending on solar
  latitude).
  TODO: should be moved to [[file:Tools/][Tools]].
- [[file:Tests/][Tests]]:
  Some very simple "test cases", which typically just test new
  features separately from the rest of the analysis programs.
- [[file:Tools/][Tools]]:
  Directory for other smaller tools, for which a separate directory in
  the root of the repository does not make sense (either used too
  infrequently or are very specific and small tools).
- [[file:VerticalShiftProblem/][VerticalShiftProblem]]:
  A simple Python tool to plot CAST log data to debug a problem with
  the belt, which slipped and caused misalignment. That problem has
  since been fixed.
  TODO: should be moved to [[file:Tools/][Tools]].

* Analysis pipeline

Some words...


* License

The code in this repository is published under the MIT license.
