title = "Test run period for differenc constraints"
# list of the run periods defined in the file, one for each set of constraints
runPeriods = ["Vthreshold_6_388", "Vthreshold_6_392", "Vthreshold_7_360"]

[Constraints]
# These are additional arbitrary constraints. They must correspond to an
# attribute that will be available for all chip groups (i.e.
# /reconstruction/run_X/chip_Y
# for this run period.
# In the chipInfo.txt file for each run period, this constraint must
# appear as a field. Say we add a constraint 'THL', then the chipInfo.txt
# file must contain `THL: value`, where the value is the one we must find
# as an attribute for the chip to help choose the right run period.
fields = ["Vthreshold_coarse", "Vthreshold_fine"]

[Vthreshold_6_388]
start = 2024-01-01
stop = 2026-01-01
# either as a sequence of run numbers
validRuns = []
# or as simply a range given as start and stop values
firstRun = 0
lastRun = 999
useCase = "Any run that has the Vthreshold_coarse = 6 and Vthreshold_fine = 388"

[Vthreshold_6_392]
start = 2024-01-01
stop = 2026-01-01
# either as a sequence of run numbers
validRuns = []
# or as simply a range given as start and stop values
firstRun = 0
lastRun = 999
useCase = "Any run that has the Vthreshold_coarse = 6 and Vthreshold_fine = 392"

[Vthreshold_7_360]
start = 2024-01-01
stop = 2026-01-01
# either as a sequence of run numbers
validRuns = []
# or as simply a range given as start and stop values
firstRun = 0
lastRun = 999
useCase = "Any run that has the Vthreshold_coarse = 7 and Vthreshold_fine = 360"